[package]
name = "quantization"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.35"
ndarray = "0.15.6"
polars = { version = "0.38.3", features = ["lazy", "temporal", "describe", "json", "parquet", "dtype-datetime"] }
